/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 buildings.gltf --transform
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/residential-building-set-99a8423808704aa3a43c2fb2492ed109
Title: Residential Building Set
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/buildings-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane_0.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_1.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_2.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_3.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_4.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_5.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_6.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_7.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_8.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_9.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_10.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_11.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_12.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_13.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_14.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_15.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_16.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_17.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_18.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_19.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_20.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_21.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_22.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_23.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_24.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_2_25.geometry} material={materials.ground} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials.hotel_glas} />
        <mesh geometry={nodes.Plane_3_1.geometry} material={materials.hotel_glas} />
        <mesh geometry={nodes.Plane_3_2.geometry} material={materials.hotel_glas} />
        <mesh geometry={nodes.Plane_3_3.geometry} material={materials.hotel_glas} />
      </group>
    </group>
  )
}

useGLTF.preload('/buildings-transformed.glb')
